version: '3'

services:

  fix-validator:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.pkg.github.com/whoan/fix-validator/fix-validator:buster-slim
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro

